#!/usr/bin/env node
/**
 * Build this configuration package: check it the way the server will, then write the zip.
 *
 *   node build.mjs [--out <directory>]        (default: ./dist next to this file; not in bundle/)
 *
 * Generated by `@nuxeo-satori/platform:config-package`. No dependencies, so it runs anywhere Node
 * 20 does. The output is byte-for-byte reproducible — fixed timestamps, entries sorted by code
 * point rather than by the machine's locale — so the same reviewed source always produces the
 * same artifact.
 *
 * Refused, each with the file and the reason. Almost all would install cleanly and then not apply.
 * The first four are the checks `ContributionRegistry` and `ConfigSnapshot` in nuxeo-agentic-core
 * make on each entry of the component XML, which the server reports in its log and leaves out:
 *   - a fragment whose layer is not `bootstrap` or `manifest`, or whose name is not letters,
 *     digits, `.`, `_` and `-`; a layout whose type or mode is not a valid name; an `<asset>`
 *     whose name is not a plain image file name. Checked on a disabled entry too, as the server
 *     does;
 *   - an enabled entry with no body, or a fragment or layout with both a `src` and inline
 *     `<json>`;
 *   - a `src` that names no packaged file in `bundle/` — a directory or a Markdown file is not one;
 *   - a fragment or layout body — a `src` file whatever its name, or inline `<json>` — that does
 *     not parse, is not an object, repeats a key, or is packaged over 1 MiB; an asset over 2 MiB.
 * And around them:
 *   - XML that is not UTF-8, or not well-formed as Nuxeo's namespace-aware parser reads it, which
 *     Nuxeo cannot load at all;
 *   - a `Nuxeo-Component` that names no packaged file in `bundle/`;
 *   - a component contributing configuration without
 *     `<require>org.nuxeo.agentic.ui.config.defaults</require>`, without which this package's
 *     fragments could register before Satori's own and lose to them;
 *   - a package name or version that is not a single file name of letters, digits, `.`, `_` and
 *     `-`, since both name the files this script writes;
 *   - a symbolic link as `bundle/` or anything in it, or as `package/` or either XML file in it,
 *     which would package bytes from outside what was reviewed — and an asset is served without
 *     authentication.
 *
 * Packaged: everything under `bundle/` except Markdown files. Every `.json` file, and any other
 * file a fragment or layout names as its `src`, is packaged compact, with a top-level `"$schema"`
 * key removed (it is for your editor, not the server).
 */
import { createHash } from 'node:crypto';
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { deflateRawSync } from 'node:zlib';

const HERE = dirname(fileURLToPath(import.meta.url));
const BUNDLE = join(HERE, 'bundle');
const PACKAGE = join(HERE, 'package');
// The server's limits and name rules: `ConfigSnapshot` and `ContributionRegistry` in
// nuxeo-agentic-core.
const MAX_JSON_BYTES = 1024 * 1024;
const MAX_ASSET_BYTES = 2 * 1024 * 1024;
const NAME = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
const TYPE = /^[A-Za-z][A-Za-z0-9_-]{0,127}$/;
const MODE = /^[a-z][a-z0-9-]{0,31}$/;
const ASSET_NAME =
  /^[A-Za-z0-9][A-Za-z0-9_-]{0,127}(?:\.[A-Za-z0-9_-]{1,32}){0,3}\.(?:svg|png|jpg|jpeg|gif|webp|ico)$/i;
const DEFAULTS_COMPONENT = 'org.nuxeo.agentic.ui.config.defaults';
const MANIFEST_ENTRY = 'META-INF/MANIFEST.MF';

const outIndex = process.argv.indexOf('--out');
if (outIndex > 0 && !process.argv[outIndex + 1]) {
  console.error('--out needs a directory');
  process.exit(2);
}
const OUT = resolve(outIndex > 0 ? process.argv[outIndex + 1] : join(HERE, 'dist'));
// A zip written into the bundle would be packaged into the next one.
if (OUT === BUNDLE || OUT.startsWith(BUNDLE + sep)) {
  console.error(`--out ${OUT} is inside bundle/, which is what gets packaged`);
  process.exit(2);
}

const problems = [];
const problem = (file, message) => problems.push(`${relative(HERE, file) || '.'}: ${message}`);

/** Whether `path` is a symbolic link, reported if so: one is refused, not followed. */
function isLink(path) {
  if (!lstatSync(path, { throwIfNoEntry: false })?.isSymbolicLink()) return false;
  problem(
    path,
    'is a symbolic link; put the file itself here, so the package holds only what was reviewed',
  );
  return true;
}

/** The files under `directory`, without following a link out of it. */
function filesUnder(directory) {
  return readdirSync(directory).flatMap((entry) => {
    const path = join(directory, entry);
    if (isLink(path)) return [];
    return lstatSync(path).isDirectory() ? filesUnder(path) : [path];
  });
}

/**
 * An XML file as a parser reads it — no byte-order mark, line endings normalised — checked for
 * well-formedness; `null`, reported, when it is missing or malformed.
 */
function readXml(file) {
  if (!existsSync(file)) {
    problem(file, 'is missing');
    return null;
  }
  let xml;
  try {
    // Strict, so a byte that is not UTF-8 is refused rather than read as U+FFFD; the decoder also
    // drops a byte-order mark.
    xml = new TextDecoder('utf-8', { fatal: true }).decode(readFileSync(file));
  } catch {
    problem(file, 'is not valid UTF-8');
    return null;
  }
  xml = xml.replace(/\r\n?/g, '\n');
  const malformed = notWellFormed(xml);
  if (malformed) {
    problem(file, `is not well-formed XML: ${malformed}`);
    return null;
  }
  return xml;
}

// XML 1.0 (fifth edition) and Namespaces in XML 1.0 — Nuxeo's parser is namespace-aware.
const XML_NAME_START =
  'A-Z_a-z\\u00C0-\\u00D6\\u00D8-\\u00F6\\u00F8-\\u02FF\\u0370-\\u037D\\u037F-\\u1FFF\\u200C\\u200D' +
  '\\u2070-\\u218F\\u2C00-\\u2FEF\\u3001-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFFD\\u{10000}-\\u{EFFFF}';
const XML_NAME_CHAR = `${XML_NAME_START}\\-.0-9\\u00B7\\u0300-\\u036F\\u203F\\u2040`;
/** XML's Name without ":", which Namespaces in XML calls an NCName. */
const NC_NAME = `[${XML_NAME_START}][${XML_NAME_CHAR}]*`;
const XML_QNAME = new RegExp(`(?:${NC_NAME}:)?${NC_NAME}`, 'uy');
const XML_PI_TARGET = new RegExp(NC_NAME, 'uy');
const XML_SPACE = /[ \t\r\n]*/y;
const XML_TEXT = /[^<&\]]+/y;
const XML_REFERENCE = /&(?:(lt|gt|amp|quot|apos)|#([0-9]+)|#x([0-9A-Fa-f]+));/y;
const XML_ILLEGAL_CHAR = /[^\t\n\r\u0020-\uD7FF\uE000-\uFFFD\u{10000}-\u{10FFFF}]/u;
const XML_DECLARATION =
  /<\?xml[ \t\r\n]+version[ \t\r\n]*=[ \t\r\n]*(["'])1\.[0-9]+\1(?:[ \t\r\n]+encoding[ \t\r\n]*=[ \t\r\n]*(["'])([A-Za-z][A-Za-z0-9._-]*)\2)?(?:[ \t\r\n]+standalone[ \t\r\n]*=[ \t\r\n]*(["'])(?:yes|no)\4)?[ \t\r\n]*\?>/y;
const XML_NAMESPACE = 'http://www.w3.org/XML/1998/namespace';
const XMLNS_NAMESPACE = 'http://www.w3.org/2000/xmlns/';

/**
 * Why `xml` is not well-formed, or `null`: XML 1.0's grammar and well-formedness constraints with
 * namespaces, as a namespace-aware parser applies them. A DOCTYPE, which none of these files
 * needs, is refused rather than interpreted, so the only entities are the five predefined ones.
 */
function notWellFormed(xml) {
  let i = 0;
  const fail = (message, at = i) => {
    throw Object.assign(new Error(`${message} at line ${xml.slice(0, at).split('\n').length}`), {
      malformed: true,
    });
  };
  const sticky = (pattern) => {
    pattern.lastIndex = i;
    const match = pattern.exec(xml);
    if (match) i = pattern.lastIndex;
    return match;
  };
  const space = () => sticky(XML_SPACE)[0].length > 0;

  const reference = () => {
    const at = i;
    const match = sticky(XML_REFERENCE);
    if (!match) fail('an "&" that starts no reference', at);
    if (match[1]) return ENTITIES[match[1]];
    const code = match[2] ? Number(match[2]) : parseInt(match[3], 16);
    if (code > 0x10ffff || XML_ILLEGAL_CHAR.test(String.fromCodePoint(code))) {
      fail('a reference to a character XML does not allow', at);
    }
    return String.fromCodePoint(code);
  };
  const comment = () => {
    const at = i;
    const end = xml.indexOf('-->', i + 4);
    if (end < 0) fail('an unterminated comment', at);
    const body = xml.slice(i + 4, end);
    if (body.includes('--') || body.endsWith('-')) fail('a comment containing "--"', at);
    i = end + 3;
  };
  const instruction = () => {
    const at = i;
    i += 2;
    const target = sticky(XML_PI_TARGET)?.[0];
    if (!target) fail('a processing instruction with no target', at);
    if (target.toLowerCase() === 'xml')
      fail('an XML declaration that is not at the start of the file', at);
    const end = xml.indexOf('?>', i);
    if (end < 0) fail('an unterminated processing instruction', at);
    if (end > i && !space()) fail('a processing instruction target not followed by a space', at);
    i = end + 2;
  };
  const misc = () => {
    for (;;) {
      space();
      if (xml.startsWith('<!--', i)) comment();
      else if (xml.startsWith('<?', i)) instruction();
      else return;
    }
  };

  const element = (scope) => {
    const at = i;
    i += 1;
    const tag = sticky(XML_QNAME)?.[0];
    if (!tag) fail('a tag with no valid element name', at);
    const attributes = [];
    for (;;) {
      const spaced = space();
      if (xml.startsWith('/>', i) || xml[i] === '>') break;
      if (i >= xml.length) fail(`an unterminated <${tag}>`, at);
      const attributeAt = i;
      const name = spaced ? sticky(XML_QNAME)?.[0] : undefined;
      if (!name) fail(`a malformed start tag <${tag}>`, attributeAt);
      space();
      if (xml[i] !== '=') fail(`a malformed attribute ${name} on <${tag}>`, attributeAt);
      i += 1;
      space();
      const quote = xml[i];
      if (quote !== '"' && quote !== "'")
        fail(`an unquoted attribute ${name} on <${tag}>`, attributeAt);
      i += 1;
      let value = '';
      while (xml[i] !== quote) {
        if (i >= xml.length) fail(`an unterminated attribute ${name} on <${tag}>`, attributeAt);
        if (xml[i] === '<') fail(`a "<" in the attribute ${name} on <${tag}>`);
        if (xml[i] === '&') {
          value += reference();
        } else {
          value += xml[i];
          i += 1;
        }
      }
      i += 1;
      if (attributes.some((other) => other.name === name)) {
        fail(`<${tag}> repeats the attribute ${name}`, attributeAt);
      }
      attributes.push({ name, value, at: attributeAt });
    }
    const empty = xml.startsWith('/>', i);
    i += empty ? 2 : 1;

    const declared = new Map(scope);
    for (const { name, value, at: where } of attributes) {
      const prefix = name === 'xmlns' ? '' : name.startsWith('xmlns:') ? name.slice(6) : null;
      if (prefix === null) continue;
      if (prefix === 'xmlns') fail('a declaration of the reserved prefix xmlns', where);
      const reserved =
        prefix === 'xml'
          ? value !== XML_NAMESPACE
          : value === XML_NAMESPACE || value === XMLNS_NAMESPACE;
      if (reserved)
        fail(`a namespace declaration of ${name} that misuses a reserved namespace`, where);
      if (prefix && value === '') fail(`an empty namespace name for the prefix ${prefix}`, where);
      declared.set(prefix, value);
    }
    const namespaceOf = (qname, where) => {
      const colon = qname.indexOf(':');
      if (colon < 0) return null;
      const prefix = qname.slice(0, colon);
      if (prefix === 'xmlns') fail(`the reserved prefix xmlns on ${qname}`, where);
      if (!declared.has(prefix)) fail(`the undeclared prefix ${prefix} on ${qname}`, where);
      return declared.get(prefix);
    };
    namespaceOf(tag, at);
    const expanded = new Set();
    for (const { name, at: where } of attributes) {
      if (name === 'xmlns' || name.startsWith('xmlns:')) continue;
      const namespace = namespaceOf(name, where);
      if (namespace === null) continue;
      const key = `${namespace} ${name.slice(name.indexOf(':') + 1)}`;
      if (expanded.has(key))
        fail(`<${tag}> has two attributes with the same namespace and name`, where);
      expanded.add(key);
    }
    if (!empty) content(tag, at, declared);
  };

  const content = (tag, at, scope) => {
    for (;;) {
      if (i >= xml.length) fail(`<${tag}> is never closed`, at);
      if (sticky(XML_TEXT)) continue;
      if (xml.startsWith('</', i)) {
        const endAt = i;
        i += 2;
        const name = sticky(XML_QNAME)?.[0];
        space();
        if (name !== tag || xml[i] !== '>') {
          fail(name ? `</${name}> closes <${tag}>` : `a malformed end tag in <${tag}>`, endAt);
        }
        i += 1;
        return;
      }
      if (xml.startsWith('<!--', i)) comment();
      else if (xml.startsWith('<![CDATA[', i)) {
        const end = xml.indexOf(']]>', i + 9);
        if (end < 0) fail('an unterminated CDATA section');
        i = end + 3;
      } else if (xml.startsWith('<?', i)) instruction();
      else if (xml.startsWith('<!', i)) fail('a declaration inside an element');
      else if (xml[i] === '<') element(scope);
      else if (xml[i] === '&') reference();
      else if (xml.startsWith(']]>', i)) fail('a "]]>" in text');
      else i += 1;
    }
  };

  try {
    const illegal = XML_ILLEGAL_CHAR.exec(xml);
    if (illegal) {
      const code = illegal[0].codePointAt(0).toString(16).toUpperCase().padStart(4, '0');
      fail(`a character XML does not allow, U+${code},`, illegal.index);
    }
    if (/^<\?xml[ \t\r\n?]/.test(xml)) {
      const declaration = sticky(XML_DECLARATION);
      if (!declaration) fail('a malformed XML declaration', 0);
      const encoding = declaration[3];
      if (encoding && !/^utf-?8$/i.test(encoding)) {
        fail(
          `an encoding of ${encoding}; write the file in UTF-8, which is how it is read here`,
          0,
        );
      }
    }
    misc();
    if (xml.startsWith('<!', i)) fail('a DOCTYPE, which none of these files needs');
    if (xml[i] !== '<') fail(i < xml.length ? 'text before the root element' : 'no root element');
    element(new Map([['xml', XML_NAMESPACE]]));
    misc();
    if (i < xml.length)
      fail(xml[i] === '<' ? 'markup after the root element' : 'text after the root element');
    return null;
  } catch (error) {
    if (error.malformed) return error.message;
    throw error;
  }
}

const isFile = (path) => lstatSync(path, { throwIfNoEntry: false })?.isFile() === true;
/** What goes into the bundle. The one predicate for packaging and for checking a `src`. */
const isPackaged = (path) => isFile(path) && !path.endsWith('.md');

/**
 * Throws on a repeated key, which `JSON.parse` would accept by keeping the last value and the
 * server refuses. Validation only — the value is taken from `JSON.parse` afterwards.
 */
function rejectDuplicateKeys(text) {
  let i = 0;
  const token = (pattern) => {
    pattern.lastIndex = i;
    const match = pattern.exec(text);
    if (!match) throw new Error(`unexpected input at offset ${i}`);
    i = pattern.lastIndex;
    return match[0];
  };
  const STRING = /"(?:[^"\\\u0000-\u001f]|\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4}))*"/y;
  const LITERAL = /-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?|true|false|null/y;
  const space = () => token(/[ \t\n\r]*/y);
  const value = (path) => {
    space();
    if (text[i] === '{') return object(path);
    if (text[i] === '[') return array(path);
    token(text[i] === '"' ? STRING : LITERAL);
  };
  const object = (path) => {
    i++;
    const seen = new Set();
    space();
    if (text[i] === '}') return void i++;
    for (;;) {
      space();
      const key = JSON.parse(token(STRING));
      if (seen.has(key)) throw new Error(`duplicate key "${key}" in ${path || 'the top level'}`);
      seen.add(key);
      space();
      token(/:/y);
      value(path ? `${path}.${key}` : key);
      space();
      if (text[i] === ',') i++;
      else if (text[i] === '}') return void i++;
      else throw new Error(`expected "," or "}" at offset ${i}`);
    }
  };
  const array = (path) => {
    i++;
    space();
    if (text[i] === ']') return void i++;
    for (let index = 0; ; index++) {
      value(`${path}[${index}]`);
      space();
      if (text[i] === ',') i++;
      else if (text[i] === ']') return void i++;
      else throw new Error(`expected "," or "]" at offset ${i}`);
    }
  };
  value('');
  space();
  if (i !== text.length) throw new Error(`unexpected input after the value at offset ${i}`);
}

/**
 * XML with its comments removed. Inside CDATA `<!--` is text, so a CDATA section is kept whole.
 * Comments do not nest; an unterminated comment or CDATA section runs to the end.
 */
function withoutComments(xml) {
  let out = '';
  let at = 0;
  for (;;) {
    const start = xml.indexOf('<!--', at);
    if (start < 0) return out + xml.slice(at);
    const cdata = xml.indexOf('<![CDATA[', at);
    if (cdata >= 0 && cdata < start) {
      const end = xml.indexOf(']]>', cdata);
      const stop = end < 0 ? xml.length : end + 3;
      out += xml.slice(at, stop);
      at = stop;
      continue;
    }
    out += xml.slice(at, start);
    const end = xml.indexOf('-->', start + 4);
    if (end < 0) return out;
    at = end + 3;
  }
}

/** The same XML with every CDATA section blanked, so markup is never matched inside text. */
const withoutCdata = (xml) =>
  xml.replace(/<!\[CDATA\[[\s\S]*?(?:\]\]>|$)/g, (section) => ' '.repeat(section.length));

const ENTITIES = { lt: '<', gt: '>', amp: '&', quot: '"', apos: "'" };

/** XML character data with its character and predefined entity references resolved. */
function decode(text) {
  return text.replace(
    /&(?:#x([0-9A-Fa-f]+)|#([0-9]+)|(lt|gt|amp|quot|apos));/g,
    (reference, hex, decimal, named) => {
      if (named) return ENTITIES[named];
      const codePoint = hex ? parseInt(hex, 16) : Number(decimal);
      return codePoint <= 0x10ffff ? String.fromCodePoint(codePoint) : reference;
    },
  );
}

/** Every `name="value"` or `name='value'` attribute of one start tag, trimmed as Nuxeo reads it. */
function attributes(tag) {
  const found = {};
  for (const [, name, , double, single] of tag.matchAll(
    /([\w:.-]+)\s*=\s*("([^"]*)"|'([^']*)')/g,
  )) {
    found[name] = decode(double ?? single).trim();
  }
  return found;
}

/**
 * The text of the `<json>` child of the `<element>` whose start tag ends at `from` — CDATA kept
 * verbatim, references resolved, trimmed — or `undefined` when it has none.
 */
function inlineJson(xml, from, element) {
  const closesElement = new RegExp(`^/${element}\\s*$`);
  let text;
  for (let at = from; ;) {
    const lt = xml.indexOf('<', at);
    if (text !== undefined) text += decode(xml.slice(at, lt < 0 ? xml.length : lt));
    if (lt < 0) return text?.trim();
    if (xml.startsWith('<![CDATA[', lt)) {
      const end = xml.indexOf(']]>', lt);
      if (text !== undefined) text += xml.slice(lt + 9, end < 0 ? xml.length : end);
      if (end < 0) return text?.trim();
      at = end + 3;
      continue;
    }
    const gt = xml.indexOf('>', lt);
    if (gt < 0) return text?.trim();
    const tag = xml.slice(lt + 1, gt);
    at = gt + 1;
    if (text === undefined) {
      if (closesElement.test(tag)) return undefined;
      if (/^json(?:[ \t\n/]|$)/.test(tag)) {
        if (tag.trimEnd().endsWith('/')) return '';
        text = '';
      }
    } else if (/^\/json\s*$/.test(tag)) {
      return text.trim();
    }
  }
}

/** The server's checks on a fragment or layout body: it parses, repeats no key, is an object. */
function parseObject(text, report) {
  let parsed;
  try {
    parsed = JSON.parse(text);
    rejectDuplicateKeys(text);
  } catch (error) {
    report(error.message);
    return null;
  }
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    report('must be a JSON object');
    return null;
  }
  return parsed;
}

/** A JSON file as packaged, compact and without `$schema`; `null` if the server would refuse it. */
function checkJson(file) {
  // A byte-order mark is skipped, as the server's parser skips it.
  const text = readFileSync(file, 'utf8').replace(/^\uFEFF/, '');
  const parsed = parseObject(text, (message) => problem(file, message));
  if (!parsed) return null;
  delete parsed.$schema;
  // The limit applies to what is packaged, which is what the server reads.
  const packaged = Buffer.from(JSON.stringify(parsed));
  if (packaged.length > MAX_JSON_BYTES) {
    problem(
      file,
      `packaged as ${packaged.length} bytes; the server refuses a fragment or layout over ${MAX_JSON_BYTES}`,
    );
    return null;
  }
  return packaged;
}

/** Why the server rejects this entry whatever its body, as `ContributionRegistry.validate` says. */
function invalidEntry(element, { name, layer, type, mode }) {
  if (element === 'fragment') {
    if (layer !== 'bootstrap' && layer !== 'manifest') {
      return `fragment "${name ?? ''}" has layer "${layer ?? ''}"; it must be "bootstrap" or "manifest"`;
    }
    if (!NAME.test(name ?? '')) {
      return `fragment name "${name ?? ''}" must be letters, digits, ".", "_" or "-"`;
    }
  } else if (element === 'layout') {
    if (!TYPE.test(type ?? '')) return `layout type "${type ?? ''}" is not a document type name`;
    if (!MODE.test(mode ?? '')) {
      return `layout mode "${mode ?? ''}" must be lower-case letters, digits or "-"`;
    }
  } else if (!ASSET_NAME.test(name ?? '')) {
    return `asset name "${name ?? ''}" must be a plain file name ending in .svg, .png, .jpg, .jpeg, .gif, .webp or .ico`;
  }
  return null;
}

// ------------------------------------------------------------------ package/

const packageXmlFile = join(PACKAGE, 'package.xml');
const installXmlFile = join(PACKAGE, 'install.xml');
const bundleIsLink = isLink(BUNDLE);
for (const path of [PACKAGE, packageXmlFile, installXmlFile]) isLink(path);
readXml(installXmlFile);
const { name: packageName, version: packageVersion } = attributes(
  /<package(?=[ \t\n/>])((?:[^>"']|"[^"]*"|'[^']*')*)>/.exec(
    withoutCdata(withoutComments(readXml(packageXmlFile) ?? '')),
  )?.[1] ?? '',
);
// Both name the files written below, so each must be a plain file name and nothing more.
const FILE_NAME = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;
if (!packageName || !packageVersion) {
  problem(packageXmlFile, '<package> needs a name and a version');
} else if (!FILE_NAME.test(packageName) || !FILE_NAME.test(packageVersion)) {
  problem(
    packageXmlFile,
    `<package> name "${packageName}" and version "${packageVersion}" must each be letters, digits, ".", "_" and "-", starting with a letter or digit`,
  );
}

// ------------------------------------------------------------------ bundle

const manifestFile = join(BUNDLE, 'META-INF', 'MANIFEST.MF');
// A manifest line longer than 72 bytes continues on the next one, which starts with a space.
const manifest = (existsSync(manifestFile) ? readFileSync(manifestFile, 'utf8') : '').replace(
  /(?:\r\n|\r|\n) /g,
  '',
);
const componentPaths = (/^Nuxeo-Component:\s*(.+?)\s*$/m.exec(manifest)?.[1] ?? '')
  .split(',')
  .map((path) => path.trim())
  .filter(Boolean);
if (componentPaths.length === 0) problem(manifestFile, 'needs a Nuxeo-Component line');

/** Fragment and layout bodies named by `src`: JSON whatever the file is called. */
const jsonBodies = new Set();

for (const componentPath of componentPaths) {
  const componentFile = resolve(BUNDLE, componentPath);
  if (!componentFile.startsWith(BUNDLE + sep) || !isPackaged(componentFile)) {
    problem(
      manifestFile,
      `Nuxeo-Component names ${componentPath}, which is not a packaged file in bundle/`,
    );
    continue;
  }
  const source = readXml(componentFile);
  if (source === null) continue;
  // Comments removed first, so a commented-out example can neither satisfy nor fail a check.
  const xml = withoutComments(source);
  // Markup is looked for here; text, including inline JSON, is read from `xml` at the same offsets.
  const markup = withoutCdata(xml);
  const contributes = [
    ...markup.matchAll(/<extension(?=[ \t\n/>])((?:[^>"']|"[^"]*"|'[^']*')*)>/g),
  ].some(([, tag]) => attributes(tag).target === 'org.nuxeo.agentic.ui.config');
  const requiresDefaults =
    /<require[ \t\n]*>[ \t\n]*org\.nuxeo\.agentic\.ui\.config\.defaults[ \t\n]*<\/require[ \t\n]*>/.test(
      markup,
    );
  if (contributes && !requiresDefaults) {
    problem(
      componentFile,
      `must <require>${DEFAULTS_COMPONENT}</require>, or its fragments may apply before Satori's defaults`,
    );
  }
  for (const match of markup.matchAll(
    /<(fragment|layout|asset)(?=[ \t\n/>])((?:[^>"']|"[^"]*"|'[^']*')*)>/g,
  )) {
    const [startTag, element, tag] = match;
    const entry = attributes(tag);
    const invalid = invalidEntry(element, entry);
    if (invalid) {
      problem(componentFile, invalid);
      continue;
    }
    const { name, layer, type, mode, src } = entry;
    const label =
      element === 'layout'
        ? `layout ${type}/${mode}`
        : `${element} "${name}"${layer ? ` in ${layer}` : ''}`;
    // Anything but "true" disables, as Nuxeo reads a boolean. A disabled entry removes an earlier
    // contribution; it has no body to check.
    if (entry.enabled !== undefined && entry.enabled.toLowerCase() !== 'true') continue;

    const json =
      element === 'asset' || tag.trimEnd().endsWith('/')
        ? undefined
        : inlineJson(xml, match.index + startTag.length, element);
    const hasJson = json !== undefined && json !== '';
    if (src && hasJson) {
      problem(componentFile, `${label} has both a src and inline JSON; use one`);
      continue;
    }
    if (!src && !hasJson) {
      problem(
        componentFile,
        `${label} has ${element === 'asset' ? 'no src' : 'neither a src nor inline JSON'}`,
      );
      continue;
    }
    if (hasJson) {
      const report = (message) => problem(componentFile, `inline JSON of ${label}: ${message}`);
      const size = Buffer.byteLength(json);
      if (parseObject(json, report) && size > MAX_JSON_BYTES) {
        report(`${size} bytes; the server refuses a fragment or layout over ${MAX_JSON_BYTES}`);
      }
      continue;
    }

    const target = resolve(BUNDLE, src);
    if (!target.startsWith(BUNDLE + sep) || !isFile(target)) {
      problem(componentFile, `src="${src}" names no file in bundle/`);
      continue;
    }
    if (!isPackaged(target)) {
      problem(componentFile, `src="${src}" names a Markdown file, which is not packaged`);
      continue;
    }
    if (element !== 'asset') {
      jsonBodies.add(target);
      continue;
    }
    const size = statSync(target).size;
    if (size > MAX_ASSET_BYTES) {
      problem(target, `${size} bytes; the server refuses an asset over ${MAX_ASSET_BYTES}`);
    }
  }
}

const entries = [];
for (const file of bundleIsLink || !existsSync(BUNDLE) ? [] : filesUnder(BUNDLE).sort()) {
  if (!isPackaged(file)) continue;
  const name = relative(BUNDLE, file).split(sep).join('/');
  const data =
    file.endsWith('.json') || jsonBodies.has(file) ? checkJson(file) : readFileSync(file);
  if (data) entries.push({ name, data });
}

if (problems.length > 0) {
  console.error(
    `\n${packageName ?? 'configuration package'}: not built — ${problems.length} problem(s)\n`,
  );
  for (const line of problems) console.error(`  - ${line}`);
  console.error('');
  process.exit(1);
}

// ------------------------------------------------------------------ zip

const CRC_TABLE = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});
function crc32(buffer) {
  let crc = 0xffffffff;
  for (const byte of buffer) crc = CRC_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

/** A deflated zip, timestamps fixed at 1980-01-01 so the bytes depend on the content alone. */
function zip(files) {
  const DOS_DATE = (0 << 9) | (1 << 5) | 1;
  const local = [];
  const central = [];
  let offset = 0;
  for (const { name, data } of files) {
    const nameBytes = Buffer.from(name, 'utf8');
    const compressed = deflateRawSync(data, { level: 9 });
    const crc = crc32(data);
    const header = Buffer.alloc(30);
    header.writeUInt32LE(0x04034b50, 0);
    header.writeUInt16LE(20, 4);
    header.writeUInt16LE(0x0800, 6);
    header.writeUInt16LE(8, 8);
    header.writeUInt16LE(0, 10);
    header.writeUInt16LE(DOS_DATE, 12);
    header.writeUInt32LE(crc, 14);
    header.writeUInt32LE(compressed.length, 18);
    header.writeUInt32LE(data.length, 22);
    header.writeUInt16LE(nameBytes.length, 26);
    local.push(header, nameBytes, compressed);

    const record = Buffer.alloc(46);
    record.writeUInt32LE(0x02014b50, 0);
    record.writeUInt16LE(20, 4);
    record.writeUInt16LE(20, 6);
    record.writeUInt16LE(0x0800, 8);
    record.writeUInt16LE(8, 10);
    record.writeUInt16LE(0, 12);
    record.writeUInt16LE(DOS_DATE, 14);
    record.writeUInt32LE(crc, 16);
    record.writeUInt32LE(compressed.length, 20);
    record.writeUInt32LE(data.length, 24);
    record.writeUInt16LE(nameBytes.length, 28);
    record.writeUInt32LE(offset, 42);
    central.push(record, nameBytes);

    offset += header.length + nameBytes.length + compressed.length;
  }
  const directory = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(files.length, 8);
  end.writeUInt16LE(files.length, 10);
  end.writeUInt32LE(directory.length, 12);
  end.writeUInt32LE(offset, 16);
  return Buffer.concat([...local, directory, end]);
}

// The manifest first, as the JAR format expects; the rest by code point, which no locale reorders.
const byCodePoint = (a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b));
entries.sort((a, b) =>
  a.name === MANIFEST_ENTRY ? -1 : b.name === MANIFEST_ENTRY ? 1 : byCodePoint(a.name, b.name),
);
const jar = zip(entries);
const archive = zip([
  { name: 'install.xml', data: readFileSync(installXmlFile) },
  { name: `install/bundles/${packageName}.jar`, data: jar },
  { name: 'package.xml', data: readFileSync(packageXmlFile) },
]);

mkdirSync(OUT, { recursive: true });
const target = join(OUT, `${packageName}-${packageVersion}.zip`);
writeFileSync(target, archive);
const sha256 = createHash('sha256').update(archive).digest('hex');
console.log(
  `built ${relative(process.cwd(), target)}  (${archive.length} bytes, sha256 ${sha256})`,
);
for (const { name } of entries) console.log(`  bundle  ${name}`);
