export {
  DEFAULT_KD_CIC_OPERATIONS,
  DEFAULT_KD_UPSTREAM_PATHS,
  KD_CIC_OPERATIONS,
  KD_UPSTREAM_PATHS,
  type KdCicOperations,
  type KdUpstreamPaths,
} from './lib/kd.config';
export { KdClientService, KdDiscoveryError } from './lib/kd-client.service';
export {
  buildIndexedReferences,
  enrichCitationsFromObjectReferences,
  extractNuxeoDocumentId,
  extractReferenceContent,
  findReferenceByIndex,
  findReferenceByKey,
  findReferenceForCitation,
  flattenObjectReferencesToCitations,
  formatReferenceExcerpt,
  formatReferenceLabel,
  getMaxCitationIndex,
  mergeCitationExcerpts,
  referenceKey,
  mergeObjectReferenceContent,
  normalizeObjectReferenceEntry,
  normalizeObjectReferences,
  parseAnswerSegments,
  referencesForObject,
  type KdAnswerSegment,
  type KdIndexedReference,
} from './lib/kd-references.util';
export type {
  KdAgentAccessRight,
  KdAgentDetails,
  KdAgentSummary,
  KdAnswerResponse,
  KdCitation,
  KdFeedbackRequest,
  KdFeedbackValue,
  KdFilterExpression,
  KdGuardrail,
  KdGuardrailGroup,
  KdModelInfo,
  KdObjectReference,
  KdObjectReferenceEntry,
  KdQuestionHistoryItem,
  KdQuestionHistoryPage,
  KdQuestionRequest,
  KdQuestionSubmission,
  KdResponseStatus,
} from './lib/kd.models';
