# Source this, then run everything from $NX_WT.
export NX_TICKET="NXENG-750"
export NX_WT="/c/Users/akoppaka/Desktop/Projects/agentic-ui-worktrees/NXENG-750"
export NX_BRANCH="fix/nxeng-750"
export NX_NUXEO_MODE="shared"
export NX_CONTAINER="nuxeo"
export NX_PORT="8080"
export NX_URL="http://localhost:8080/nuxeo"
export NX_DATA_ROOT="/default-domain/workspaces/NXENG-750"
export NX_APP_PORT="4218"
export NX_PROXY="apps/nuxeo-ui/proxy.conf.ticket-nxeng-750.json"
export TICKET="NXENG-750"
export EVID="/c/Users/akoppaka/Desktop/agentic-ui-evidence/NXENG-750/fix"
export APP_URL="http://localhost:4218"
