/**
 * Layer 0 bootstrap configuration — the part of the configuration that has to be
 * readable *before* the user authenticates.
 *
 * It therefore holds only what the shell needs in order to reach the server and
 * paint a branded login page: where Nuxeo is, what the product is called, which
 * theme to start in, and where to find the runtime manifest. Everything a
 * customer changes after login belongs in the runtime manifest instead, so that
 * it inherits Nuxeo's versioning, audit and ACLs.
 *
 * The constants here are the **packaged defaults**. The deployed, editable copy
 * lives *beside* the application bundle rather than inside it: the marketplace
 * installer copies the `web` directory with `overwrite="true"`, so anything a
 * customer edits within the bundle is destroyed on the next upgrade.
 */

/** CSS custom properties applied to `<html>` while a theme is active. */
export type AppThemeTokens = Readonly<Record<string, string>>;

/** Swatches shown on the theme picker tile, so a new theme is previewable without a build. */
export interface AppThemePreview {
  readonly sidebar: string;
  readonly surface: string;
  readonly header: string;
  readonly accent: string;
  readonly tile: string;
}

export interface AppThemeConfig {
  readonly id: string;
  readonly label: string;
  /**
   * Catalogue key for the theme's name. When it resolves, it is shown instead of `label`, which
   * stays the fallback. A configured `label` without a `labelKey` replaces both, so a customer's
   * own name for a packaged theme is shown as written.
   */
  readonly labelKey?: string;
  /**
   * Which of the compiled `html[data-app-theme=...]` palettes this theme builds
   * on. Material palettes are generated by a Sass mixin and so cannot come from
   * JSON; `tokens` is the part a customer can change without a rebuild.
   */
  readonly base: string;
  readonly preview: AppThemePreview;
  readonly tokens: AppThemeTokens;
}

/** A deployment's own logo, shown instead of the Satori marks in the header and on the login page. */
export interface AppBrandingLogo {
  /**
   * As written in `bootstrap.json`: a file name or relative path, resolved against the directory
   * `bootstrap.json` is served from; an `https:` URL; or a `data:image/` URI. Any other form keeps
   * the Satori marks — see `resolveBrandingLogoUrl` for the check on where it actually points.
   */
  readonly src: string;
  /** Accessible name for the login page's brand link. Empty falls back to `applicationTitle`. */
  readonly alt: string;
}

export interface AppBrandingConfig {
  /** Shown in the application header. */
  readonly applicationTitle: string;
  /** Written to `document.title`. */
  readonly documentTitle: string;
  /** `null` keeps the Satori marks. */
  readonly logo: AppBrandingLogo | null;
}

/**
 * ARender annotation viewer endpoints, or `null` when ARender is not deployed.
 *
 * `null` means **no annotation viewer**, not "fall back to a compiled default" — there are no
 * compiled defaults any more. `ARENDER_CONFIG` is nullable and defaults to `null`, and the UI shows
 * "Annotations are not available".
 */
export interface AppARenderConfig {
  readonly viewerOrigin: string;
  readonly nuxeoInternalUrl: string;
}

/**
 * Overrides for third-party integration wiring — deployment facts rather than
 * customer preferences, which is why they are in the bootstrap half.
 *
 * The Content Intelligence Connector operation maps are partial by design: a
 * customer who renamed one automation operation should not have to restate the
 * other five.
 */
export interface AppIntegrationsConfig {
  readonly arender: AppARenderConfig | null;
  readonly knowledgeDiscoveryOperations: Readonly<Record<string, string>>;
  readonly knowledgeEnrichmentOperations: Readonly<Record<string, string>>;
}

/** `null` means "keep the compiled default", which mirrors Nuxeo's own `nuxeo.session.timeout`. */
export interface AppSessionConfig {
  readonly idleTimeoutMs: number | null;
  readonly warningBeforeMs: number | null;
}

export interface AppSsoEndpointConfig {
  readonly id: string;
  readonly label: string;
  readonly path: string;
}

export interface AppSsoConfig {
  readonly endpoints: readonly AppSsoEndpointConfig[];
  readonly postLoginPath: string | null;
  readonly returnQueryParam: string | null;
}

export interface AppBootstrapConfig {
  /**
   * Origin for Nuxeo REST calls from the browser. `''` keeps requests relative,
   * which is correct both behind the dev proxy and for same-origin production.
   */
  readonly nuxeoApiOrigin: string;
  /**
   * Nuxeo as seen by external clients (Nuxeo Drive, ARender). `null` derives it
   * from the browser location, which is correct for same-origin deployments.
   */
  readonly nuxeoServerUrl: string | null;
  /** Prefix under which the `AI.*` automation operations are served. */
  readonly aiBackendUrl: string;
  /** Repository path of the Nuxeo document holding the runtime manifest. */
  readonly manifestDocumentPath: string;
  /** Document property read as the manifest JSON payload. */
  readonly manifestDocumentProperty: string;
  readonly branding: AppBrandingConfig;
  readonly defaultThemeId: string;
  readonly themes: readonly AppThemeConfig[];
  readonly defaultLanguage: string;
  readonly availableLanguages: readonly string[];
  readonly integrations: AppIntegrationsConfig;
  readonly session: AppSessionConfig;
  readonly sso: AppSsoConfig;
}

/**
 * The four palettes compiled into `styles.scss`. Their `tokens` maps are empty
 * because the packaged themes are fully described by the Sass mixins; the maps
 * exist so a customer can rebrand any of them, or add a fifth theme, in JSON.
 */
export const DEFAULT_APP_THEMES: readonly AppThemeConfig[] = [
  {
    id: 'nuxeo',
    labelKey: 'settings.themes.name.nuxeo',
    label: 'Nuxeo',
    base: 'nuxeo',
    preview: {
      sidebar: '#1a237e',
      surface: '#f5f5f5',
      header: '#e8eaf6',
      accent: '#2196f3',
      tile: '#dce3f5',
    },
    tokens: {},
  },
  {
    id: 'dark',
    labelKey: 'settings.themes.name.dark',
    label: 'Dark',
    base: 'dark',
    preview: {
      sidebar: '#1e2a3a',
      surface: '#0d1117',
      header: '#161b22',
      accent: '#3d5afe',
      tile: '#21262d',
    },
    tokens: {},
  },
  {
    id: 'kawaii',
    labelKey: 'settings.themes.name.kawaii',
    label: 'Kawaii',
    base: 'kawaii',
    preview: {
      sidebar: '#880e4f',
      surface: '#fce4ec',
      header: '#f8bbd9',
      accent: '#e91e63',
      tile: '#f5c6d6',
    },
    tokens: {},
  },
  {
    id: 'light',
    labelKey: 'settings.themes.name.light',
    label: 'Light',
    base: 'light',
    preview: {
      sidebar: '#37474f',
      surface: '#eceff1',
      header: '#cfd8dc',
      accent: '#00bcd4',
      tile: '#b0bec5',
    },
    tokens: {},
  },
];

/**
 * Reproduces today's compiled-in behaviour exactly, so a deployment that ships
 * no configuration file at all is indistinguishable from the current release.
 */
export const DEFAULT_APP_BOOTSTRAP_CONFIG: AppBootstrapConfig = {
  nuxeoApiOrigin: '',
  nuxeoServerUrl: null,
  aiBackendUrl: '/nuxeo',
  manifestDocumentPath: '/default-domain/config/agentic-ui',
  manifestDocumentProperty: 'note:note',
  branding: {
    // These two differ today: the shell header falls back to "Hyland Nuxeo"
    // while `index.html` sets the browser tab to "Nuxeo Platform". Both are
    // reproduced exactly so that adopting configuration changes nothing.
    applicationTitle: 'Hyland Nuxeo',
    documentTitle: 'Nuxeo Platform',
    logo: null,
  },
  defaultThemeId: 'nuxeo',
  themes: DEFAULT_APP_THEMES,
  defaultLanguage: 'en',
  // The locales a catalogue actually ships for, in `apps/nuxeo-ui/public/i18n/`. Listing a
  // locale here that has no catalogue would advertise a language the application cannot
  // render, which `checkAdvertisedLocalesShip` fails.
  //
  // Six ship besides English — fr, de, ja, nl, th and zh (Simplified Chinese, Crowdin's
  // `zh-CN`) — each pulled from Crowdin once approved. It does NOT mean every key is translated:
  // `setFallbackLang('en')` covers gaps, and a Crowdin pull fills every unapproved string with its
  // English source. `checkTranslationCatalogues` warns on a missing key and fails only on one
  // `en.json` does not have. See D8d in docs/i18n-localization-plan.md.
  //
  // Nothing renders this list yet: there is no language picker (NXSAT-294), and only the config
  // parser reads it. A deployment selects its language through `defaultLanguage`.
  //
  // Adding a language here also means adding it to `download_translations_args` in
  // .github/workflows/crowdin-pull.yaml, which downloads only the languages the app ships.
  availableLanguages: ['en', 'fr', 'de', 'ja', 'nl', 'th', 'zh'],
  integrations: {
    arender: null,
    knowledgeDiscoveryOperations: {},
    knowledgeEnrichmentOperations: {},
  },
  session: {
    idleTimeoutMs: null,
    warningBeforeMs: null,
  },
  sso: {
    // Empty on purpose. `main` commented these same two entries out of
    // `nuxeo-sso.providers.ts` — "hidden until SAML is ready for Satori beta" — because the
    // buttons rendered but no registration existed behind them. Shipping azure and okta as
    // the packaged default would put two non-working buttons back on the login page for
    // every deployment, so the decision is preserved here.
    //
    // The mechanism is the improvement rather than the values: registration IDs must match
    // the Nuxeo OpenID/SAML setup, which is exactly the per-deployment fact that used to
    // require editing our source. A deployment adds its own under `sso.endpoints` in
    // `bootstrap.json`, with no rebuild:
    //
    //   "sso": { "endpoints": [
    //     { "id": "azure", "label": "Log In With Azure SAML",
    //       "path": "/nuxeo/oauth2/authorization/azure" }
    //   ] }
    endpoints: [],
    postLoginPath: '/dashboard',
    returnQueryParam: 'requestedUrl',
  },
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function readString(source: Record<string, unknown>, key: string, fallback: string): string {
  const value = source[key];
  return typeof value === 'string' ? value : fallback;
}

function readNullableString(
  source: Record<string, unknown>,
  key: string,
  fallback: string | null,
): string | null {
  const value = source[key];
  if (typeof value === 'string') return value;
  return value === null ? null : fallback;
}

/** Keeps only string-valued entries: a token map with an object in it would emit `[object Object]` into CSS. */
function readTokens(value: unknown): AppThemeTokens {
  if (!isRecord(value)) return {};
  const tokens: Record<string, string> = {};
  for (const [key, raw] of Object.entries(value)) {
    if (typeof raw === 'string') tokens[key] = raw;
  }
  return tokens;
}

function readStringArray(
  source: Record<string, unknown>,
  key: string,
  fallback: readonly string[],
): readonly string[] {
  const value = source[key];
  if (!Array.isArray(value)) return fallback;
  const entries = value.filter((entry): entry is string => typeof entry === 'string');
  return entries.length > 0 ? entries : fallback;
}

function mergeTheme(base: AppThemeConfig, patch: Record<string, unknown>): AppThemeConfig {
  const preview = isRecord(patch['preview']) ? patch['preview'] : {};
  const relabelled = typeof patch['label'] === 'string';
  const labelKey = readString(patch, 'labelKey', relabelled ? '' : (base.labelKey ?? ''));
  return {
    id: readString(patch, 'id', base.id),
    label: readString(patch, 'label', base.label),
    ...(labelKey ? { labelKey } : {}),
    base: readString(patch, 'base', base.base),
    preview: {
      sidebar: readString(preview, 'sidebar', base.preview.sidebar),
      surface: readString(preview, 'surface', base.preview.surface),
      header: readString(preview, 'header', base.preview.header),
      accent: readString(preview, 'accent', base.preview.accent),
      tile: readString(preview, 'tile', base.preview.tile),
    },
    tokens: { ...base.tokens, ...readTokens(patch['tokens']) },
  };
}

/**
 * Merge configured themes over the packaged ones by `id`, so a customer can
 * restyle one theme without having to restate the other three, and can append
 * new ones. An entry without a usable `id` is dropped rather than guessed at.
 */
function mergeThemes(base: readonly AppThemeConfig[], value: unknown): readonly AppThemeConfig[] {
  if (!Array.isArray(value)) return base;
  const merged = base.map((theme) => ({ ...theme }));
  for (const entry of value) {
    if (!isRecord(entry)) continue;
    const id = entry['id'];
    if (typeof id !== 'string' || id.trim() === '') continue;
    const existing = merged.findIndex((theme) => theme.id === id);
    if (existing >= 0) {
      merged[existing] = mergeTheme(merged[existing] as AppThemeConfig, entry);
    } else {
      merged.push(
        mergeTheme(
          {
            id,
            label: id,
            base: DEFAULT_APP_BOOTSTRAP_CONFIG.defaultThemeId,
            preview: { sidebar: '', surface: '', header: '', accent: '', tile: '' },
            tokens: {},
          },
          entry,
        ),
      );
    }
  }
  return merged;
}

function readPositiveNumber(
  source: Record<string, unknown>,
  key: string,
  fallback: number | null,
): number | null {
  const value = source[key];
  if (typeof value === 'number' && Number.isFinite(value) && value > 0) return value;
  return value === null ? null : fallback;
}

/** Only string entries survive: an operation ID that is not a string cannot be called. */
function readStringRecord(value: unknown): Readonly<Record<string, string>> {
  if (!isRecord(value)) return {};
  const record: Record<string, string> = {};
  for (const [key, entry] of Object.entries(value)) {
    if (typeof entry === 'string' && entry.trim() !== '') record[key] = entry;
  }
  return record;
}

/**
 * An ARender configuration only if the manifest supplies **both** endpoints non-blank, otherwise
 * `null`.
 *
 * Falls back to `base` per field so a partial override still merges over an existing complete
 * configuration; it is the *result* that must be complete, not the patch.
 */
function completeARenderConfig(
  patch: Record<string, unknown>,
  base: AppARenderConfig | null,
): AppARenderConfig | null {
  const viewerOrigin = readString(patch, 'viewerOrigin', base?.viewerOrigin ?? '').trim();
  const nuxeoInternalUrl = readString(
    patch,
    'nuxeoInternalUrl',
    base?.nuxeoInternalUrl ?? '',
  ).trim();
  if (!viewerOrigin || !nuxeoInternalUrl) return null;
  return { viewerOrigin, nuxeoInternalUrl };
}

function mergeIntegrations(base: AppIntegrationsConfig, value: unknown): AppIntegrationsConfig {
  if (!isRecord(value)) return base;
  const arender = value['arender'];
  return {
    // Both endpoints are required: half an ARender configuration is worse than none, because a
    // blank endpoint is not inert. `fetch('')` resolves against the *application's own* origin, so
    // an availability probe would report a viewer that is not deployed, and the URL built from it
    // would be same-origin.
    //
    // This used to be a comment only. The merge filled a missing half from
    // `base.arender?.… ?? ''`, and since `base.arender` is `null` that produced an object with one
    // blank endpoint — exactly the state the comment said was rejected. `ARenderService` guards it
    // too, and deliberately keeps doing so, but the layer that claims to enforce the contract now
    // actually does.
    // `null` is handled before the record check, matching `readNullableString`'s
    // `value === null ? null : fallback`. Without it, `{ integrations: { arender: null } }` fell
    // through to `base.arender` and preserved whatever was already configured — so a
    // higher-priority manifest could not turn the integration *off*, only reconfigure it. That
    // contradicts the contract this change introduced, which is that `null` means no annotation
    // viewer.
    arender:
      arender === null
        ? null
        : isRecord(arender)
          ? completeARenderConfig(arender, base.arender)
          : base.arender,
    knowledgeDiscoveryOperations: {
      ...base.knowledgeDiscoveryOperations,
      ...readStringRecord(value['knowledgeDiscoveryOperations']),
    },
    knowledgeEnrichmentOperations: {
      ...base.knowledgeEnrichmentOperations,
      ...readStringRecord(value['knowledgeEnrichmentOperations']),
    },
  };
}

function mergeSession(base: AppSessionConfig, value: unknown): AppSessionConfig {
  if (!isRecord(value)) return base;
  return {
    idleTimeoutMs: readPositiveNumber(value, 'idleTimeoutMs', base.idleTimeoutMs),
    warningBeforeMs: readPositiveNumber(value, 'warningBeforeMs', base.warningBeforeMs),
  };
}

function readSsoEndpoints(
  base: readonly AppSsoEndpointConfig[],
  value: unknown,
): readonly AppSsoEndpointConfig[] {
  if (!Array.isArray(value)) return base;
  const endpoints: AppSsoEndpointConfig[] = [];
  for (const entry of value) {
    if (!isRecord(entry)) continue;
    const id = entry['id'];
    const path = entry['path'];
    // A button with no ID or nowhere to send the browser is not a login option.
    if (typeof id !== 'string' || id.trim() === '') continue;
    if (typeof path !== 'string' || !path.startsWith('/')) continue;
    endpoints.push({ id, path, label: readString(entry, 'label', id) });
  }
  return endpoints;
}

/**
 * Early rejection of a configured logo `src`, on the string as written.
 *
 * Not the security boundary — {@link resolveBrandingLogoUrl} is, because it checks the URL the
 * browser will actually load. This only refuses what is wrong whatever it resolves to: control
 * characters and backslashes (the URL parser deletes or rewrites them, so they disguise a path),
 * a `data:` URI that is not an image or carries no payload, a scheme other than `https:`, and an
 * absolute path or `..` segment (including `%2e%2e`) in a relative one.
 */
function isAcceptedLogoSrc(src: string): boolean {
  if (src.includes('\\') || [...src].some((char) => char < ' ' || char === '\u007f')) return false;
  if (/^data:/i.test(src)) return /^data:image\/[a-z0-9.+-]+(?:;[^,]*)?,./i.test(src);
  if (/^[a-z][a-z0-9+.-]*:/i.test(src)) {
    if (!/^https:\/\/[^/]/i.test(src)) return false;
    try {
      return new URL(src).protocol === 'https:';
    } catch {
      return false;
    }
  }
  if (src.startsWith('/')) return false;
  const path = src.split(/[?#]/, 1)[0] ?? '';
  return !path.replace(/%2e/gi, '.').split('/').includes('..');
}

/**
 * `null` clears a logo an earlier layer set; anything unusable keeps `base`, so a malformed entry
 * degrades to the packaged marks rather than to a broken image.
 */
function readLogo(value: unknown, base: AppBrandingLogo | null): AppBrandingLogo | null {
  if (value === null) return null;
  if (!isRecord(value)) return base;
  const src = typeof value['src'] === 'string' ? value['src'].trim() : '';
  if (!src || !isAcceptedLogoSrc(src)) return base;
  const alt = value['alt'];
  return { src, alt: typeof alt === 'string' ? alt.trim() : '' };
}

/**
 * The URL an `<img>` may load for a configured logo, or `null` when it could reach something other
 * than a static asset.
 *
 * A relative `src` resolves against the directory `bootstrap.json` was read from, because the
 * installer replaces the application bundle on every upgrade and leaves that directory alone.
 *
 * The check runs on the **resolved** URL, after the parser has dropped tabs and newlines and
 * collapsed `..` and `%2e%2e` — the forms a check on the raw string can be talked past. On any
 * origin that serves Nuxeo the URL must stay inside the configuration directory: anywhere else
 * there may be a REST endpoint, which an `<img>` requests with the session cookie and without the
 * HTTP interceptor. Elsewhere only `https:` is allowed, so a CDN logo still works.
 *
 * @param nuxeoOrigins origins that serve Nuxeo besides the one `configUrl` is on
 */
export function resolveBrandingLogoUrl(
  src: string,
  configUrl: string,
  nuxeoOrigins: readonly string[] = [],
): string | null {
  let url: URL;
  try {
    url = new URL(src, configUrl);
  } catch {
    return null;
  }
  if (url.protocol === 'data:') return url.href;

  const config = new URL(configUrl);
  if (url.origin === config.origin) {
    return url.pathname.startsWith(new URL('.', config).pathname) ? url.href : null;
  }
  if (nuxeoOrigins.includes(url.origin)) return null;
  return url.protocol === 'https:' ? url.href : null;
}

/**
 * Every origin that serves Nuxeo for this deployment: the application's own, which proxies or is
 * Nuxeo, plus a configured `nuxeoApiOrigin` and `nuxeoServerUrl`. Unparseable values are skipped.
 */
export function nuxeoOriginsOf(config: AppBootstrapConfig, baseUri: string): string[] {
  const origins = new Set<string>();
  for (const candidate of [baseUri, config.nuxeoApiOrigin, config.nuxeoServerUrl]) {
    if (!candidate) continue;
    try {
      origins.add(new URL(candidate).origin);
    } catch {
      // A relative or malformed value names no other origin.
    }
  }
  return [...origins];
}

function mergeSso(base: AppSsoConfig, value: unknown): AppSsoConfig {
  if (!isRecord(value)) return base;
  return {
    endpoints: readSsoEndpoints(base.endpoints, value['endpoints']),
    postLoginPath: readNullableString(value, 'postLoginPath', base.postLoginPath),
    returnQueryParam: readNullableString(value, 'returnQueryParam', base.returnQueryParam),
  };
}

/**
 * Overlay a parsed configuration document onto the packaged defaults.
 *
 * Deliberately total: any input, including `null`, a string, or an object whose
 * fields have the wrong types, yields a usable configuration. A malformed
 * configuration file must degrade to the packaged behaviour rather than prevent
 * the application from starting.
 */
export function mergeBootstrapConfig(base: AppBootstrapConfig, patch: unknown): AppBootstrapConfig {
  if (!isRecord(patch)) return base;
  const branding = isRecord(patch['branding']) ? patch['branding'] : {};
  return {
    nuxeoApiOrigin: readString(patch, 'nuxeoApiOrigin', base.nuxeoApiOrigin),
    nuxeoServerUrl: readNullableString(patch, 'nuxeoServerUrl', base.nuxeoServerUrl),
    aiBackendUrl: readString(patch, 'aiBackendUrl', base.aiBackendUrl),
    manifestDocumentPath: readString(patch, 'manifestDocumentPath', base.manifestDocumentPath),
    manifestDocumentProperty: readString(
      patch,
      'manifestDocumentProperty',
      base.manifestDocumentProperty,
    ),
    branding: {
      applicationTitle: readString(branding, 'applicationTitle', base.branding.applicationTitle),
      documentTitle: readString(branding, 'documentTitle', base.branding.documentTitle),
      logo: readLogo(branding['logo'], base.branding.logo),
    },
    defaultThemeId: readString(patch, 'defaultThemeId', base.defaultThemeId),
    themes: mergeThemes(base.themes, patch['themes']),
    defaultLanguage: readString(patch, 'defaultLanguage', base.defaultLanguage),
    availableLanguages: readStringArray(patch, 'availableLanguages', base.availableLanguages),
    integrations: mergeIntegrations(base.integrations, patch['integrations']),
    session: mergeSession(base.session, patch['session']),
    sso: mergeSso(base.sso, patch['sso']),
  };
}

/** The configured theme, or the default one, or the first one — never `undefined`. */
export function resolveTheme(config: AppBootstrapConfig, id: string | null): AppThemeConfig {
  return (
    config.themes.find((theme) => theme.id === id) ??
    config.themes.find((theme) => theme.id === config.defaultThemeId) ??
    (config.themes[0] as AppThemeConfig | undefined) ??
    (DEFAULT_APP_THEMES[0] as AppThemeConfig)
  );
}
