/**
 * Layer 0 bootstrap configuration — the part of the configuration that has to be
 * readable *before* the user authenticates.
 *
 * It therefore holds only what the shell needs in order to reach the server and
 * paint a branded login page: where Nuxeo is, what the product is called, which
 * theme to start in, and where to find the runtime manifest. Everything a
 * customer changes after login belongs in the runtime manifest instead, so that
 * it inherits Nuxeo's versioning, audit and ACLs.
 *
 * The constants here are the **packaged defaults**. The deployed, editable copy
 * lives *beside* the application bundle rather than inside it: the marketplace
 * installer copies the `web` directory with `overwrite="true"`, so anything a
 * customer edits within the bundle is destroyed on the next upgrade.
 */

/** CSS custom properties applied to `<html>` while a theme is active. */
export type AppThemeTokens = Readonly<Record<string, string>>;

/** Swatches shown on the theme picker tile, so a new theme is previewable without a build. */
export interface AppThemePreview {
  readonly sidebar: string;
  readonly surface: string;
  readonly header: string;
  readonly accent: string;
  readonly tile: string;
}

export interface AppThemeConfig {
  readonly id: string;
  readonly label: string;
  /**
   * Which of the compiled `html[data-app-theme=...]` palettes this theme builds
   * on. Material palettes are generated by a Sass mixin and so cannot come from
   * JSON; `tokens` is the part a customer can change without a rebuild.
   */
  readonly base: string;
  readonly preview: AppThemePreview;
  readonly tokens: AppThemeTokens;
}

export interface AppBrandingConfig {
  /** Shown in the application header. */
  readonly applicationTitle: string;
  /** Written to `document.title`. */
  readonly documentTitle: string;
}

/** ARender annotation viewer endpoints. `null` keeps the values compiled into the client. */
export interface AppARenderConfig {
  readonly viewerOrigin: string;
  readonly nuxeoInternalUrl: string;
}

/**
 * Overrides for third-party integration wiring — deployment facts rather than
 * customer preferences, which is why they are in the bootstrap half.
 *
 * The Content Intelligence Connector operation maps are partial by design: a
 * customer who renamed one automation operation should not have to restate the
 * other five.
 */
export interface AppIntegrationsConfig {
  readonly arender: AppARenderConfig | null;
  readonly knowledgeDiscoveryOperations: Readonly<Record<string, string>>;
  readonly knowledgeEnrichmentOperations: Readonly<Record<string, string>>;
}

/** `null` means "keep the compiled default", which mirrors Nuxeo's own `nuxeo.session.timeout`. */
export interface AppSessionConfig {
  readonly idleTimeoutMs: number | null;
  readonly warningBeforeMs: number | null;
}

export interface AppSsoEndpointConfig {
  readonly id: string;
  readonly label: string;
  readonly path: string;
}

export interface AppSsoConfig {
  readonly endpoints: readonly AppSsoEndpointConfig[];
  readonly postLoginPath: string | null;
  readonly returnQueryParam: string | null;
}

export interface AppBootstrapConfig {
  /**
   * Origin for Nuxeo REST calls from the browser. `''` keeps requests relative,
   * which is correct both behind the dev proxy and for same-origin production.
   */
  readonly nuxeoApiOrigin: string;
  /**
   * Nuxeo as seen by external clients (Nuxeo Drive, ARender). `null` derives it
   * from the browser location, which is correct for same-origin deployments.
   */
  readonly nuxeoServerUrl: string | null;
  /** Prefix under which the `AI.*` automation operations are served. */
  readonly aiBackendUrl: string;
  /** Repository path of the Nuxeo document holding the runtime manifest. */
  readonly manifestDocumentPath: string;
  /** Document property read as the manifest JSON payload. */
  readonly manifestDocumentProperty: string;
  readonly branding: AppBrandingConfig;
  readonly defaultThemeId: string;
  readonly themes: readonly AppThemeConfig[];
  readonly defaultLanguage: string;
  readonly availableLanguages: readonly string[];
  readonly integrations: AppIntegrationsConfig;
  readonly session: AppSessionConfig;
  readonly sso: AppSsoConfig;
}

/**
 * The four palettes compiled into `styles.scss`. Their `tokens` maps are empty
 * because the packaged themes are fully described by the Sass mixins; the maps
 * exist so a customer can rebrand any of them, or add a fifth theme, in JSON.
 */
export const DEFAULT_APP_THEMES: readonly AppThemeConfig[] = [
  {
    id: 'nuxeo',
    label: 'Nuxeo',
    base: 'nuxeo',
    preview: {
      sidebar: '#1a237e',
      surface: '#f5f5f5',
      header: '#e8eaf6',
      accent: '#2196f3',
      tile: '#dce3f5',
    },
    tokens: {},
  },
  {
    id: 'dark',
    label: 'Dark',
    base: 'dark',
    preview: {
      sidebar: '#1e2a3a',
      surface: '#0d1117',
      header: '#161b22',
      accent: '#3d5afe',
      tile: '#21262d',
    },
    tokens: {},
  },
  {
    id: 'kawaii',
    label: 'Kawaii',
    base: 'kawaii',
    preview: {
      sidebar: '#880e4f',
      surface: '#fce4ec',
      header: '#f8bbd9',
      accent: '#e91e63',
      tile: '#f5c6d6',
    },
    tokens: {},
  },
  {
    id: 'light',
    label: 'Light',
    base: 'light',
    preview: {
      sidebar: '#37474f',
      surface: '#eceff1',
      header: '#cfd8dc',
      accent: '#00bcd4',
      tile: '#b0bec5',
    },
    tokens: {},
  },
];

/**
 * Reproduces today's compiled-in behaviour exactly, so a deployment that ships
 * no configuration file at all is indistinguishable from the current release.
 */
export const DEFAULT_APP_BOOTSTRAP_CONFIG: AppBootstrapConfig = {
  nuxeoApiOrigin: '',
  nuxeoServerUrl: null,
  aiBackendUrl: '/nuxeo',
  manifestDocumentPath: '/default-domain/config/agentic-ui',
  manifestDocumentProperty: 'note:note',
  branding: {
    // These two differ today: the shell header falls back to "Hyland Nuxeo"
    // while `index.html` sets the browser tab to "Nuxeo Platform". Both are
    // reproduced exactly so that adopting configuration changes nothing.
    applicationTitle: 'Hyland Nuxeo',
    documentTitle: 'Nuxeo Platform',
  },
  defaultThemeId: 'nuxeo',
  themes: DEFAULT_APP_THEMES,
  defaultLanguage: 'en',
  availableLanguages: ['en'],
  integrations: {
    arender: null,
    knowledgeDiscoveryOperations: {},
    knowledgeEnrichmentOperations: {},
  },
  session: {
    idleTimeoutMs: null,
    warningBeforeMs: null,
  },
  sso: {
    // Empty on purpose. `main` commented these same two entries out of
    // `nuxeo-sso.providers.ts` — "hidden until SAML is ready for Satori beta" — because the
    // buttons rendered but no registration existed behind them. Shipping azure and okta as
    // the packaged default would put two non-working buttons back on the login page for
    // every deployment, so the decision is preserved here.
    //
    // The mechanism is the improvement rather than the values: registration IDs must match
    // the Nuxeo OpenID/SAML setup, which is exactly the per-deployment fact that used to
    // require editing our source. A deployment adds its own under `sso.endpoints` in
    // `bootstrap.json`, with no rebuild:
    //
    //   "sso": { "endpoints": [
    //     { "id": "azure", "label": "Log In With Azure SAML",
    //       "path": "/nuxeo/oauth2/authorization/azure" }
    //   ] }
    endpoints: [],
    postLoginPath: '/dashboard',
    returnQueryParam: 'requestedUrl',
  },
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function readString(source: Record<string, unknown>, key: string, fallback: string): string {
  const value = source[key];
  return typeof value === 'string' ? value : fallback;
}

function readNullableString(
  source: Record<string, unknown>,
  key: string,
  fallback: string | null,
): string | null {
  const value = source[key];
  if (typeof value === 'string') return value;
  return value === null ? null : fallback;
}

/** Keeps only string-valued entries: a token map with an object in it would emit `[object Object]` into CSS. */
function readTokens(value: unknown): AppThemeTokens {
  if (!isRecord(value)) return {};
  const tokens: Record<string, string> = {};
  for (const [key, raw] of Object.entries(value)) {
    if (typeof raw === 'string') tokens[key] = raw;
  }
  return tokens;
}

function readStringArray(
  source: Record<string, unknown>,
  key: string,
  fallback: readonly string[],
): readonly string[] {
  const value = source[key];
  if (!Array.isArray(value)) return fallback;
  const entries = value.filter((entry): entry is string => typeof entry === 'string');
  return entries.length > 0 ? entries : fallback;
}

function mergeTheme(base: AppThemeConfig, patch: Record<string, unknown>): AppThemeConfig {
  const preview = isRecord(patch['preview']) ? patch['preview'] : {};
  return {
    id: readString(patch, 'id', base.id),
    label: readString(patch, 'label', base.label),
    base: readString(patch, 'base', base.base),
    preview: {
      sidebar: readString(preview, 'sidebar', base.preview.sidebar),
      surface: readString(preview, 'surface', base.preview.surface),
      header: readString(preview, 'header', base.preview.header),
      accent: readString(preview, 'accent', base.preview.accent),
      tile: readString(preview, 'tile', base.preview.tile),
    },
    tokens: { ...base.tokens, ...readTokens(patch['tokens']) },
  };
}

/**
 * Merge configured themes over the packaged ones by `id`, so a customer can
 * restyle one theme without having to restate the other three, and can append
 * new ones. An entry without a usable `id` is dropped rather than guessed at.
 */
function mergeThemes(base: readonly AppThemeConfig[], value: unknown): readonly AppThemeConfig[] {
  if (!Array.isArray(value)) return base;
  const merged = base.map((theme) => ({ ...theme }));
  for (const entry of value) {
    if (!isRecord(entry)) continue;
    const id = entry['id'];
    if (typeof id !== 'string' || id.trim() === '') continue;
    const existing = merged.findIndex((theme) => theme.id === id);
    if (existing >= 0) {
      merged[existing] = mergeTheme(merged[existing] as AppThemeConfig, entry);
    } else {
      merged.push(
        mergeTheme(
          {
            id,
            label: id,
            base: DEFAULT_APP_BOOTSTRAP_CONFIG.defaultThemeId,
            preview: { sidebar: '', surface: '', header: '', accent: '', tile: '' },
            tokens: {},
          },
          entry,
        ),
      );
    }
  }
  return merged;
}

function readPositiveNumber(
  source: Record<string, unknown>,
  key: string,
  fallback: number | null,
): number | null {
  const value = source[key];
  if (typeof value === 'number' && Number.isFinite(value) && value > 0) return value;
  return value === null ? null : fallback;
}

/** Only string entries survive: an operation ID that is not a string cannot be called. */
function readStringRecord(value: unknown): Readonly<Record<string, string>> {
  if (!isRecord(value)) return {};
  const record: Record<string, string> = {};
  for (const [key, entry] of Object.entries(value)) {
    if (typeof entry === 'string' && entry.trim() !== '') record[key] = entry;
  }
  return record;
}

function mergeIntegrations(base: AppIntegrationsConfig, value: unknown): AppIntegrationsConfig {
  if (!isRecord(value)) return base;
  const arender = value['arender'];
  return {
    // Both endpoints are required: half an ARender configuration is worse than none.
    arender: isRecord(arender)
      ? {
          viewerOrigin: readString(arender, 'viewerOrigin', base.arender?.viewerOrigin ?? ''),
          nuxeoInternalUrl: readString(
            arender,
            'nuxeoInternalUrl',
            base.arender?.nuxeoInternalUrl ?? '',
          ),
        }
      : base.arender,
    knowledgeDiscoveryOperations: {
      ...base.knowledgeDiscoveryOperations,
      ...readStringRecord(value['knowledgeDiscoveryOperations']),
    },
    knowledgeEnrichmentOperations: {
      ...base.knowledgeEnrichmentOperations,
      ...readStringRecord(value['knowledgeEnrichmentOperations']),
    },
  };
}

function mergeSession(base: AppSessionConfig, value: unknown): AppSessionConfig {
  if (!isRecord(value)) return base;
  return {
    idleTimeoutMs: readPositiveNumber(value, 'idleTimeoutMs', base.idleTimeoutMs),
    warningBeforeMs: readPositiveNumber(value, 'warningBeforeMs', base.warningBeforeMs),
  };
}

function readSsoEndpoints(
  base: readonly AppSsoEndpointConfig[],
  value: unknown,
): readonly AppSsoEndpointConfig[] {
  if (!Array.isArray(value)) return base;
  const endpoints: AppSsoEndpointConfig[] = [];
  for (const entry of value) {
    if (!isRecord(entry)) continue;
    const id = entry['id'];
    const path = entry['path'];
    // A button with no ID or nowhere to send the browser is not a login option.
    if (typeof id !== 'string' || id.trim() === '') continue;
    if (typeof path !== 'string' || !path.startsWith('/')) continue;
    endpoints.push({ id, path, label: readString(entry, 'label', id) });
  }
  return endpoints;
}

function mergeSso(base: AppSsoConfig, value: unknown): AppSsoConfig {
  if (!isRecord(value)) return base;
  return {
    endpoints: readSsoEndpoints(base.endpoints, value['endpoints']),
    postLoginPath: readNullableString(value, 'postLoginPath', base.postLoginPath),
    returnQueryParam: readNullableString(value, 'returnQueryParam', base.returnQueryParam),
  };
}

/**
 * Overlay a parsed configuration document onto the packaged defaults.
 *
 * Deliberately total: any input, including `null`, a string, or an object whose
 * fields have the wrong types, yields a usable configuration. A malformed
 * configuration file must degrade to the packaged behaviour rather than prevent
 * the application from starting.
 */
export function mergeBootstrapConfig(base: AppBootstrapConfig, patch: unknown): AppBootstrapConfig {
  if (!isRecord(patch)) return base;
  const branding = isRecord(patch['branding']) ? patch['branding'] : {};
  return {
    nuxeoApiOrigin: readString(patch, 'nuxeoApiOrigin', base.nuxeoApiOrigin),
    nuxeoServerUrl: readNullableString(patch, 'nuxeoServerUrl', base.nuxeoServerUrl),
    aiBackendUrl: readString(patch, 'aiBackendUrl', base.aiBackendUrl),
    manifestDocumentPath: readString(patch, 'manifestDocumentPath', base.manifestDocumentPath),
    manifestDocumentProperty: readString(
      patch,
      'manifestDocumentProperty',
      base.manifestDocumentProperty,
    ),
    branding: {
      applicationTitle: readString(branding, 'applicationTitle', base.branding.applicationTitle),
      documentTitle: readString(branding, 'documentTitle', base.branding.documentTitle),
    },
    defaultThemeId: readString(patch, 'defaultThemeId', base.defaultThemeId),
    themes: mergeThemes(base.themes, patch['themes']),
    defaultLanguage: readString(patch, 'defaultLanguage', base.defaultLanguage),
    availableLanguages: readStringArray(patch, 'availableLanguages', base.availableLanguages),
    integrations: mergeIntegrations(base.integrations, patch['integrations']),
    session: mergeSession(base.session, patch['session']),
    sso: mergeSso(base.sso, patch['sso']),
  };
}

/** The configured theme, or the default one, or the first one — never `undefined`. */
export function resolveTheme(config: AppBootstrapConfig, id: string | null): AppThemeConfig {
  return (
    config.themes.find((theme) => theme.id === id) ??
    config.themes.find((theme) => theme.id === config.defaultThemeId) ??
    (config.themes[0] as AppThemeConfig | undefined) ??
    (DEFAULT_APP_THEMES[0] as AppThemeConfig)
  );
}
