# Source this, then run everything from $NX_WT.
export NX_TICKET="NXENG-950"
export NX_WT="/c/Users/akoppaka/Desktop/Projects/agentic-ui-worktrees/NXENG-950"
export NX_BRANCH="fix/nxeng-950"
export NX_NUXEO_MODE="shared"
export NX_CONTAINER="nuxeo"
export NX_PORT="8080"
export NX_URL="http://localhost:8080/nuxeo"
export NX_DATA_ROOT="/default-domain/workspaces/NXENG-950"
export NX_APP_PORT="4215"
export NX_PROXY="apps/nuxeo-ui/proxy.conf.ticket-nxeng-950.json"
export TICKET="NXENG-950"
export EVID="/c/Users/akoppaka/Desktop/agentic-ui-evidence/NXENG-950/fix"
export APP_URL="http://localhost:4215"
